JokerTable = {
    ace = {
        ['monkey_ace'] = { path = 0, tier = 0 },
        ['rapid_fire'] = { path = 1, tier = 1 },
        ['lots_more_darts'] = { path = 1, tier = 2 },
        ['fighter_plane'] = { path = 1, tier = 3 },
        ['operation_dart_storm'] = { path = 1, tier = 4 },
        ['sky_shredder'] = { path = 1, tier = 5 },
        ['exploding_pineapple'] = { path = 2, tier = 1 },
        ['spy_plane'] = { path = 2, tier = 2 },
        ['bomber_ace'] = { path = 2, tier = 3 },
        ['ground_zero'] = { path = 2, tier = 4 },
        ['tsar_bomba'] = { path = 2, tier = 5 },
        ['sharper_darts'] = { path = 3, tier = 1 },
        ['centered_path'] = { path = 3, tier = 2 },
        ['neva_miss_targeting'] = { path = 3, tier = 3 },
        ['spectre'] = { path = 3, tier = 4 },
        ['flying_fortress'] = { path = 3, tier = 5 },
        ['goliath_doomship'] = { path = 0, tier = 6 },
    },
    alch = {
        ['alchemist'] = { path = 0, tier = 0 },
        ['larger_potions'] = { path = 1, tier = 1 },
        ['acidic_mixture_dip'] = { path = 1, tier = 2 },
        ['berserker_brew'] = { path = 1, tier = 3 },
        ['stronger_stimulant'] = { path = 1, tier = 4 },
        ['permanent_brew'] = { path = 1, tier = 5 },
        ['stronger_acid'] = { path = 2, tier = 1 },
        ['perishing_potions'] = { path = 2, tier = 2 },
        ['unstable_concoction'] = { path = 2, tier = 3 },
        ['transforming_tonic'] = { path = 2, tier = 4 },
        ['total_transformation'] = { path = 2, tier = 5 },
        ['faster_throwing_alchemist'] = { path = 3, tier = 1 },
        ['acid_pools'] = { path = 3, tier = 2 },
        ['lead_to_gold'] = { path = 3, tier = 3 },
        ['rubber_to_gold'] = { path = 3, tier = 4 },
        ['bloon_master_alchemist'] = { path = 3, tier = 5 },
    },
    beast = {
        ['beast_handler'] = { path = 0, tier = 0 },
        ['piranha'] = { path = 1, tier = 1 },
        ['barracuda'] = { path = 1, tier = 2 },
        ['great_white'] = { path = 1, tier = 3 },
        ['orca'] = { path = 1, tier = 4 },
        ['megalodon'] = { path = 1, tier = 5 },
        ['microraptor'] = { path = 2, tier = 1 },
        ['adasaurus'] = { path = 2, tier = 2 },
        ['velociraptor'] = { path = 2, tier = 3 },
        ['tyrannosaurus_rex'] = { path = 2, tier = 4 },
        ['giganotosaurus'] = { path = 2, tier = 5 },
        ['gyrfalcon'] = { path = 3, tier = 1 },
        ['horned_owl'] = { path = 3, tier = 2 },
        ['golden_eagle'] = { path = 3, tier = 3 },
        ['giant_condor'] = { path = 3, tier = 4 },
        ['pouakai'] = { path = 3, tier = 5 },
    },
    boat = {
        ['monkey_buccaneer'] = { path = 0, tier = 0 },
        ['faster_shooting_buccaneer'] = { path = 1, tier = 1 },
        ['double_shot_buccaneer'] = { path = 1, tier = 2 },
        ['destroyer'] = { path = 1, tier = 3 },
        ['aircraft_carrier'] = { path = 1, tier = 4 },
        ['carrier_flagship'] = { path = 1, tier = 5 },
        ['grape_shot'] = { path = 2, tier = 1 },
        ['hot_shot'] = { path = 2, tier = 2 },
        ['cannon_ship'] = { path = 2, tier = 3 },
        ['monkey_pirates'] = { path = 2, tier = 4 },
        ['pirate_lord'] = { path = 2, tier = 5 },
        ['long_range'] = { path = 3, tier = 1 },
        ['crows_nest'] = { path = 3, tier = 2 },
        ['merchantman'] = { path = 3, tier = 3 },
        ['favored_trades'] = { path = 3, tier = 4 },
        ['trade_empire'] = { path = 3, tier = 5 },
        ['navarch_of_the_seas'] = { path = 0, tier = 6 },
    },
    bomb = {
        ['bomb_shooter'] = { path = 0, tier = 0 },
        ['bigger_bombs'] = { path = 1, tier = 1 },
        ['heavy_bombs'] = { path = 1, tier = 2 },
        ['really_big_bombs'] = { path = 1, tier = 3 },
        ['bloon_impact'] = { path = 1, tier = 4 },
        ['bloon_crush'] = { path = 1, tier = 5 },
        ['faster_reload_bomb'] = { path = 2, tier = 1 },
        ['missile_launcher'] = { path = 2, tier = 2 },
        ['moab_mauler'] = { path = 2, tier = 3 },
        ['moab_assassin'] = { path = 2, tier = 4 },
        ['moab_eliminator'] = { path = 2, tier = 5 },
        ['extra_range'] = { path = 3, tier = 1 },
        ['frag_bombs'] = { path = 3, tier = 2 },
        ['cluster_bombs'] = { path = 3, tier = 3 },
        ['recursive_cluster'] = { path = 3, tier = 4 },
        ['bomb_blitz'] = { path = 3, tier = 5 },
        ['ballistic_obliteration_missile_bunker'] = { path = 0, tier = 6 },
    },
    boomer = {
        ['boomerang_monkey'] = { path = 0, tier = 0 },
        ['improved_rangs'] = { path = 1, tier = 1 },
        ['glaives'] = { path = 1, tier = 2 },
        ['glaive_ricochet'] = { path = 1, tier = 3 },
        ['moar_glaives'] = { path = 1, tier = 4 },
        ['glaive_lord'] = { path = 1, tier = 5 },
        ['faster_throwing_boomerang'] = { path = 2, tier = 1 },
        ['faster_rangs'] = { path = 2, tier = 2 },
        ['bionic_boomerang'] = { path = 2, tier = 3 },
        ['turbo_charge'] = { path = 2, tier = 4 },
        ['perma_charge'] = { path = 2, tier = 5 },
        ['long_range_rangs'] = { path = 3, tier = 1 },
        ['red_hot_rangs'] = { path = 3, tier = 2 },
        ['kylie_boomerang'] = { path = 3, tier = 3 },
        ['moab_press'] = { path = 3, tier = 4 },
        ['moab_domination'] = { path = 3, tier = 5 },
        ['glaive_dominus'] = { path = 0, tier = 6 },
    },
    dart = {
        ['dart_monkey'] = { path = 0, tier = 0 },
        ['sharp_shots'] = { path = 1, tier = 1 },
        ['razor_sharp_shots'] = { path = 1, tier = 2 },
        ['spike_o_pult'] = { path = 1, tier = 3 },
        ['juggernaut'] = { path = 1, tier = 4 },
        ['ultra_juggernaut'] = { path = 1, tier = 5 },
        ['quick_shots'] = { path = 2, tier = 1 },
        ['very_quick_shots'] = { path = 2, tier = 2 },
        ['triple_shot'] = { path = 2, tier = 3 },
        ['super_monkey_fan_club'] = { path = 2, tier = 4 },
        ['plasma_monkey_fan_club'] = { path = 2, tier = 5 },
        ['long_range_darts'] = { path = 3, tier = 1 },
        ['enhanced_eyesight'] = { path = 3, tier = 2 },
        ['crossbow'] = { path = 3, tier = 3 },
        ['sharp_shooter'] = { path = 3, tier = 4 },
        ['crossbow_master'] = { path = 3, tier = 5 },
        ['apex_plasma_master'] = { path = 0, tier = 6 },
    },
    dartling = {
        ['dartling_gunner'] = { path = 0, tier = 0 },
        ['focused_firing'] = { path = 1, tier = 1 },
        ['laser_shock'] = { path = 1, tier = 2 },
        ['laser_cannon'] = { path = 1, tier = 3 },
        ['plasma_accelerator'] = { path = 1, tier = 4 },
        ['ray_of_doom'] = { path = 1, tier = 5 },
        ['advanced_targeting'] = { path = 2, tier = 1 },
        ['faster_barrel_spin'] = { path = 2, tier = 2 },
        ['hydra_rocket_pods'] = { path = 2, tier = 3 },
        ['rocket_storm'] = { path = 2, tier = 4 },
        ['mad'] = { path = 2, tier = 5 },
        ['faster_swivel'] = { path = 3, tier = 1 },
        ['powerful_darts'] = { path = 3, tier = 2 },
        ['buckshot'] = { path = 3, tier = 3 },
        ['bloon_area_denial_system'] = { path = 3, tier = 4 },
        ['bloon_exclusion_zone'] = { path = 3, tier = 5 },
    },
    desp = {
        ['desperado'] = { path = 0, tier = 0 },
        ['quickdraw'] = { path = 1, tier = 1 },
        ['standoff'] = { path = 1, tier = 2 },
        ['big_iron'] = { path = 1, tier = 3 },
        ['twin_sixes'] = { path = 1, tier = 4 },
        ['the_blazing_sun'] = { path = 1, tier = 5 },
        ['eagle_eye'] = { path = 2, tier = 1 },
        ['bullseye'] = { path = 2, tier = 2 },
        ['deadeye'] = { path = 2, tier = 3 },
        ['bounty_hunter'] = { path = 2, tier = 4 },
        ['golden_justice'] = { path = 2, tier = 5 },
        ['wanderer'] = { path = 3, tier = 1 },
        ['nomad'] = { path = 3, tier = 2 },
        ['enforcer'] = { path = 3, tier = 3 },
        ['avenger'] = { path = 3, tier = 4 },
        ['the_desert_phantom'] = { path = 3, tier = 5 },
    },
    druid = {
        ['druid'] = { path = 0, tier = 0 },
        ['hard_thorns'] = { path = 1, tier = 1 },
        ['heart_of_thunder'] = { path = 1, tier = 2 },
        ['druid_of_the_storm'] = { path = 1, tier = 3 },
        ['ball_lightning'] = { path = 1, tier = 4 },
        ['monarch_of_storms'] = { path = 1, tier = 5 },
        ['thorn_swarm'] = { path = 2, tier = 1 },
        ['heart_of_oak'] = { path = 2, tier = 2 },
        ['druid_of_the_jungle'] = { path = 2, tier = 3 },
        ['jungles_bounty'] = { path = 2, tier = 4 },
        ['spirit_of_the_forest'] = { path = 2, tier = 5 },
        ['druidic_reach'] = { path = 3, tier = 1 },
        ['heart_of_vengeance'] = { path = 3, tier = 2 },
        ['druid_of_wrath'] = { path = 3, tier = 3 },
        ['poplust'] = { path = 3, tier = 4 },
        ['avatar_of_wrath'] = { path = 3, tier = 5 },
        ['root_of_all_nature'] = { path = 0, tier = 6 },
    },
    engi = {
        ['engineer_monkey'] = { path = 0, tier = 0 },
        ['sentry_gun'] = { path = 1, tier = 1 },
        ['faster_engineering'] = { path = 1, tier = 2 },
        ['sprockets'] = { path = 1, tier = 3 },
        ['sentry_expert'] = { path = 1, tier = 4 },
        ['sentry_champion'] = { path = 1, tier = 5 },
        ['larger_service_area'] = { path = 2, tier = 1 },
        ['deconstruction'] = { path = 2, tier = 2 },
        ['cleansing_foam'] = { path = 2, tier = 3 },
        ['overclock'] = { path = 2, tier = 4 },
        ['ultraboost'] = { path = 2, tier = 5 },
        ['oversize_nails'] = { path = 3, tier = 1 },
        ['pin'] = { path = 3, tier = 2 },
        ['double_gun'] = { path = 3, tier = 3 },
        ['bloon_trap'] = { path = 3, tier = 4 },
        ['xxxl_trap'] = { path = 3, tier = 5 },
        ['master_builder'] = { path = 0, tier = 6 },
    },
    farm = {
        ['banana_farm'] = { path = 0, tier = 0 },
        ['increased_production'] = { path = 1, tier = 1 },
        ['greater_production'] = { path = 1, tier = 2 },
        ['banana_plantation'] = { path = 1, tier = 3 },
        ['banana_research_facility'] = { path = 1, tier = 4 },
        ['banana_central'] = { path = 1, tier = 5 },
        ['long_life_bananas'] = { path = 2, tier = 1 },
        ['valuable_bananas'] = { path = 2, tier = 2 },
        ['monkey_bank'] = { path = 2, tier = 3 },
        ['imf_loan'] = { path = 2, tier = 4 },
        ['monkey_nomics'] = { path = 2, tier = 5 },
        ['ez_collect'] = { path = 3, tier = 1 },
        ['banana_salvage'] = { path = 3, tier = 2 },
        ['marketplace'] = { path = 3, tier = 3 },
        ['central_market'] = { path = 3, tier = 4 },
        ['monkey_wall_street'] = { path = 3, tier = 5 },
    },
    glue = {
        ['glue_gunner'] = { path = 0, tier = 0 },
        ['glue_soak'] = { path = 1, tier = 1 },
        ['corrosive_glue'] = { path = 1, tier = 2 },
        ['bloon_dissolver'] = { path = 1, tier = 3 },
        ['bloon_liquefier'] = { path = 1, tier = 4 },
        ['the_bloon_solver'] = { path = 1, tier = 5 },
        ['bigger_globs'] = { path = 2, tier = 1 },
        ['glue_splatter'] = { path = 2, tier = 2 },
        ['glue_hose'] = { path = 2, tier = 3 },
        ['glue_strike'] = { path = 2, tier = 4 },
        ['glue_storm'] = { path = 2, tier = 5 },
        ['stickier_glue'] = { path = 3, tier = 1 },
        ['stronger_glue'] = { path = 3, tier = 2 },
        ['moab_glue'] = { path = 3, tier = 3 },
        ['relentless_glue'] = { path = 3, tier = 4 },
        ['super_glue'] = { path = 3, tier = 5 },
    },
    heli = {
        ['heli_pilot'] = { path = 0, tier = 0 },
        ['quad_darts'] = { path = 1, tier = 1 },
        ['pursuit'] = { path = 1, tier = 2 },
        ['razor_rotors'] = { path = 1, tier = 3 },
        ['apache_dartship'] = { path = 1, tier = 4 },
        ['apache_prime'] = { path = 1, tier = 5 },
        ['bigger_jets'] = { path = 2, tier = 1 },
        ['ifr'] = { path = 2, tier = 2 },
        ['downdraft'] = { path = 2, tier = 3 },
        ['support_chinook'] = { path = 2, tier = 4 },
        ['special_poperations'] = { path = 2, tier = 5 },
        ['faster_darts'] = { path = 3, tier = 1 },
        ['faster_firing'] = { path = 3, tier = 2 },
        ['moab_shove'] = { path = 3, tier = 3 },
        ['comanche_defense'] = { path = 3, tier = 4 },
        ['comanche_commander'] = { path = 3, tier = 5 },
    },
    ice = {
        ['ice_monkey'] = { path = 0, tier = 0 },
        ['permafrost'] = { path = 1, tier = 1 },
        ['cold_snap'] = { path = 1, tier = 2 },
        ['ice_shards'] = { path = 1, tier = 3 },
        ['embrittlement'] = { path = 1, tier = 4 },
        ['super_brittle'] = { path = 1, tier = 5 },
        ['enhanced_freeze'] = { path = 2, tier = 1 },
        ['deep_freeze'] = { path = 2, tier = 2 },
        ['arctic_wind'] = { path = 2, tier = 3 },
        ['snowstorm'] = { path = 2, tier = 4 },
        ['absolute_zero'] = { path = 2, tier = 5 },
        ['larger_radius'] = { path = 3, tier = 1 },
        ['re_freeze'] = { path = 3, tier = 2 },
        ['cryo_cannon'] = { path = 3, tier = 3 },
        ['icicles'] = { path = 3, tier = 4 },
        ['icicle_impale'] = { path = 3, tier = 5 },
        ['herald_of_everfrost'] = { path = 0, tier = 6 },
    },
    merm = {
        ['mermonkey'] = { path = 0, tier = 0 },
        ['trident_efficiency'] = { path = 1, tier = 1 },
        ['trident_swiftness'] = { path = 1, tier = 2 },
        ['abyss_dweller'] = { path = 1, tier = 3 },
        ['abyssal_warrior'] = { path = 1, tier = 4 },
        ['lord_of_the_abyss'] = { path = 1, tier = 5 },
        ['sharper_prongs'] = { path = 2, tier = 1 },
        ['tidal_chill'] = { path = 2, tier = 2 },
        ['riptide_champion'] = { path = 2, tier = 3 },
        ['arctic_knight'] = { path = 2, tier = 4 },
        ['popseidon'] = { path = 2, tier = 5 },
        ['echosense_precision'] = { path = 3, tier = 1 },
        ['echosense_network'] = { path = 3, tier = 2 },
        ['alluring_melody'] = { path = 3, tier = 3 },
        ['symphonic_resonance'] = { path = 3, tier = 4 },
        ['the_final_harmonic'] = { path = 3, tier = 5 },
    },
    mortar = {
        ['mortar_monkey'] = { path = 0, tier = 0 },
        ['bigger_blast'] = { path = 1, tier = 1 },
        ['bloon_buster'] = { path = 1, tier = 2 },
        ['shell_shock'] = { path = 1, tier = 3 },
        ['the_big_one'] = { path = 1, tier = 4 },
        ['the_biggest_one'] = { path = 1, tier = 5 },
        ['faster_reload'] = { path = 2, tier = 1 },
        ['rapid_reload'] = { path = 2, tier = 2 },
        ['heavy_shells'] = { path = 2, tier = 3 },
        ['artillery_battery'] = { path = 2, tier = 4 },
        ['pop_and_awe'] = { path = 2, tier = 5 },
        ['increased_accuracy'] = { path = 3, tier = 1 },
        ['burny_stuff'] = { path = 3, tier = 2 },
        ['signal_flare'] = { path = 3, tier = 3 },
        ['shattering_shells'] = { path = 3, tier = 4 },
        ['blooncineration'] = { path = 3, tier = 5 },
    },
    ninja = {
        ['ninja_monkey'] = { path = 0, tier = 0 },
        ['ninja_discipline'] = { path = 1, tier = 1 },
        ['sharp_shurikens'] = { path = 1, tier = 2 },
        ['double_shot_ninja'] = { path = 1, tier = 3 },
        ['bloonjitsu'] = { path = 1, tier = 4 },
        ['grandmaster_ninja'] = { path = 1, tier = 5 },
        ['distraction'] = { path = 2, tier = 1 },
        ['counter_espionage'] = { path = 2, tier = 2 },
        ['shinobi_tactics'] = { path = 2, tier = 3 },
        ['bloon_sabotage'] = { path = 2, tier = 4 },
        ['grand_saboteur'] = { path = 2, tier = 5 },
        ['seeking_shuriken'] = { path = 3, tier = 1 },
        ['caltrops'] = { path = 3, tier = 2 },
        ['flash_bomb'] = { path = 3, tier = 3 },
        ['sticky_bomb'] = { path = 3, tier = 4 },
        ['master_bomber'] = { path = 3, tier = 5 },
        ['ascended_shadow'] = { path = 0, tier = 6 },
    },
    sniper = {
        ['sniper_monkey'] = { path = 0, tier = 0 },
        ['full_metal_jacket'] = { path = 1, tier = 1 },
        ['large_calibre'] = { path = 1, tier = 2 },
        ['deadly_precision'] = { path = 1, tier = 3 },
        ['maim_moab'] = { path = 1, tier = 4 },
        ['cripple_moab'] = { path = 1, tier = 5 },
        ['night_vision_goggles'] = { path = 2, tier = 1 },
        ['shrapnel_shot'] = { path = 2, tier = 2 },
        ['bouncing_bullet'] = { path = 2, tier = 3 },
        ['supply_drop'] = { path = 2, tier = 4 },
        ['elite_sniper'] = { path = 2, tier = 5 },
        ['fast_firing_sniper'] = { path = 3, tier = 1 },
        ['even_faster_firing'] = { path = 3, tier = 2 },
        ['semi_automatic'] = { path = 3, tier = 3 },
        ['full_auto_rifle'] = { path = 3, tier = 4 },
        ['elite_defender'] = { path = 3, tier = 5 },
    },
    spac = {
        ['spike_factory'] = { path = 0, tier = 0 },
        ['bigger_stacks'] = { path = 1, tier = 1 },
        ['white_hot_spikes'] = { path = 1, tier = 2 },
        ['spiked_balls'] = { path = 1, tier = 3 },
        ['spiked_mines'] = { path = 1, tier = 4 },
        ['super_mines'] = { path = 1, tier = 5 },
        ['faster_production'] = { path = 2, tier = 1 },
        ['even_faster_production'] = { path = 2, tier = 2 },
        ['moab_shredr'] = { path = 2, tier = 3 },
        ['spike_storm'] = { path = 2, tier = 4 },
        ['carpet_of_spikes'] = { path = 2, tier = 5 },
        ['long_reach'] = { path = 3, tier = 1 },
        ['smart_spikes'] = { path = 3, tier = 2 },
        ['long_life_spikes'] = { path = 3, tier = 3 },
        ['deadly_spikes'] = { path = 3, tier = 4 },
        ['perma_spike'] = { path = 3, tier = 5 },
        ['mega_massive_munitions_factory'] = { path = 0, tier = 6 },
    },
    sub = {
        ['monkey_sub'] = { path = 0, tier = 0 },
        ['longer_range'] = { path = 1, tier = 1 },
        ['advanced_intel'] = { path = 1, tier = 2 },
        ['submerge_and_support'] = { path = 1, tier = 3 },
        ['bloontonium_reactor'] = { path = 1, tier = 4 },
        ['energizer'] = { path = 1, tier = 5 },
        ['barbed_darts'] = { path = 2, tier = 1 },
        ['heat_tipped_darts'] = { path = 2, tier = 2 },
        ['ballistic_missile'] = { path = 2, tier = 3 },
        ['first_strike_capability'] = { path = 2, tier = 4 },
        ['pre_emptive_strike'] = { path = 2, tier = 5 },
        ['twin_guns'] = { path = 3, tier = 1 },
        ['airburst_darts'] = { path = 3, tier = 2 },
        ['triple_guns'] = { path = 3, tier = 3 },
        ['armor_piercing_darts'] = { path = 3, tier = 4 },
        ['sub_commander'] = { path = 3, tier = 5 },
        ['nautic_siege_core'] = { path = 0, tier = 6 },
    },
    super = {
        ['super_monkey'] = { path = 0, tier = 0 },
        ['laser_blasts'] = { path = 1, tier = 1 },
        ['plasma_blasts'] = { path = 1, tier = 2 },
        ['sun_avatar'] = { path = 1, tier = 3 },
        ['sun_temple'] = { path = 1, tier = 4 },
        ['true_sun_god'] = { path = 1, tier = 5 },
        ['super_range'] = { path = 2, tier = 1 },
        ['epic_range'] = { path = 2, tier = 2 },
        ['robo_monkey'] = { path = 2, tier = 3 },
        ['tech_terror'] = { path = 2, tier = 4 },
        ['the_anti_bloon'] = { path = 2, tier = 5 },
        ['knockback'] = { path = 3, tier = 1 },
        ['ultravision'] = { path = 3, tier = 2 },
        ['dark_knight'] = { path = 3, tier = 3 },
        ['dark_champion'] = { path = 3, tier = 4 },
        ['legend_of_the_night'] = { path = 3, tier = 5 },
        ['vengeful_true_sun_god'] = { path = 0, tier = 5 },
    },
    tack = {
        ['tack_shooter'] = { path = 0, tier = 0 },
        ['faster_shooting_tack'] = { path = 1, tier = 1 },
        ['even_faster_shooting'] = { path = 1, tier = 2 },
        ['hot_shots'] = { path = 1, tier = 3 },
        ['ring_of_fire'] = { path = 1, tier = 4 },
        ['inferno_ring'] = { path = 1, tier = 5 },
        ['long_range_tacks'] = { path = 2, tier = 1 },
        ['super_range_tacks'] = { path = 2, tier = 2 },
        ['blade_shooter'] = { path = 2, tier = 3 },
        ['blade_maelstrom'] = { path = 2, tier = 4 },
        ['super_maelstrom'] = { path = 2, tier = 5 },
        ['more_tacks'] = { path = 3, tier = 1 },
        ['even_more_tacks'] = { path = 3, tier = 2 },
        ['tack_sprayer'] = { path = 3, tier = 3 },
        ['overdrive'] = { path = 3, tier = 4 },
        ['the_tack_zone'] = { path = 3, tier = 5 },
        ['crucible_of_steel_and_flame'] = { path = 0, tier = 6 },
    },
    village = {
        ['monkey_village'] = { path = 0, tier = 0 },
        ['bigger_radius'] = { path = 1, tier = 1 },
        ['jungle_drums'] = { path = 1, tier = 2 },
        ['primary_training'] = { path = 1, tier = 3 },
        ['primary_mentoring'] = { path = 1, tier = 4 },
        ['primary_expertise'] = { path = 1, tier = 5 },
        ['grow_blocker'] = { path = 2, tier = 1 },
        ['radar_scanner'] = { path = 2, tier = 2 },
        ['monkey_intelligence_bureau'] = { path = 2, tier = 3 },
        ['call_to_arms'] = { path = 2, tier = 4 },
        ['homeland_defense'] = { path = 2, tier = 5 },
        ['monkey_business'] = { path = 3, tier = 1 },
        ['monkey_commerce'] = { path = 3, tier = 2 },
        ['monkey_town'] = { path = 3, tier = 3 },
        ['monkey_city'] = { path = 3, tier = 4 },
        ['monkeyopolis'] = { path = 3, tier = 5 },
    },
    warden = {
        ['skywarden'] = { path = 0, tier = 0 },
        ['aerial_attunement'] = { path = 1, tier = 1 },
        ['zephyr_sense'] = { path = 1, tier = 2 },
        ['wind_weaver'] = { path = 1, tier = 3 },
        ['galesage'] = { path = 1, tier = 4 },
        ['farwind_seer'] = { path = 1, tier = 5 },
        ['storms_pulse'] = { path = 2, tier = 1 },
        ['thundering_arc'] = { path = 2, tier = 2 },
        ['galvanic_conduit'] = { path = 2, tier = 3 },
        ['thunders_decree'] = { path = 2, tier = 4 },
        ['stormwrath_archon'] = { path = 2, tier = 5 },
        ['shatterpoint'] = { path = 3, tier = 1 },
        ['icebore'] = { path = 3, tier = 2 },
        ['coldchain'] = { path = 3, tier = 3 },
        ['frozen_verdict'] = { path = 3, tier = 4 },
        ['winters_mercy'] = { path = 3, tier = 5 },
    },
    wizard = {
        ['wizard_monkey'] = { path = 0, tier = 0 },
        ['guided_magic'] = { path = 1, tier = 1 },
        ['arcane_blast'] = { path = 1, tier = 2 },
        ['arcane_mastery'] = { path = 1, tier = 3 },
        ['arcane_spike'] = { path = 1, tier = 4 },
        ['archmage'] = { path = 1, tier = 5 },
        ['fireball'] = { path = 2, tier = 1 },
        ['wall_of_fire'] = { path = 2, tier = 2 },
        ['dragons_breath'] = { path = 2, tier = 3 },
        ['summon_phoenix'] = { path = 2, tier = 4 },
        ['wizard_lord_phoenix'] = { path = 2, tier = 5 },
        ['intense_magic'] = { path = 3, tier = 1 },
        ['monkey_sense'] = { path = 3, tier = 2 },
        ['shimmer'] = { path = 3, tier = 3 },
        ['necromancer'] = { path = 3, tier = 4 },
        ['prince_of_darkness'] = { path = 3, tier = 5 },
        ['magus_perfectus'] = { path = 0, tier = 6 },
    },
}
