[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
if blind and blind.name then
    self:change_colour()
else
    self:change_colour(G.C.BLACK)
end
'''
position = "after"
payload = '''
if G.GAME.modifiers.double_blind_size then
    self.mult = self.mult*2
elseif G.GAME.modifiers.triple_blind_size then
    self.mult = self.mult*3
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if G.GAME.modifiers.double_blind_size then
    blind_amt = blind_amt*2
elseif G.GAME.modifiers.triple_blind_size then
    blind_amt = blind_amt*3
end
'''
match_indent = true
times = 1