[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Challenge stake change
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.FUNCS.start_run(e, {stake = 1, challenge = G.CHALLENGES[e.config.id]})"
position = 'at'
payload = "G.FUNCS.start_run(e, {stake = get_challenge_stake(e), challenge = G.CHALLENGES[e.config.id]})"
match_indent = true

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
if self.debuff.h_size_ge and #cards < self.debuff.h_size_ge then
    self.triggered = true
    return true
end
'''
position = "before"
payload = '''
if G.GAME.modifiers.crash_of_the_titans then
    if #cards <= 4 then 
        self.triggered = true
        return true
    end

    local text,disp_text,poker_hands,scoring_hand,non_loc_disp_text = G.FUNCS.get_poker_hand_info(cards)
    
    local final_scoring_hand = {}
    for i=1, #cards do
        local card = cards[i]
        local splashed = SMODS.always_scores(card) or next(find_joker('Splash')) or next(find_joker('Echosense Precision'))
        local unsplashed = SMODS.never_scores(card)
        if not splashed then
            for _, scoring_card in pairs(scoring_hand) do
                if scoring_card == card then splashed = true end
            end
        end
        local effects = {}
        SMODS.calculate_context({modify_scoring_hand = true, other_card = card, full_hand = cards, scoring_hand = scoring_hand, in_scoring = true}, effects)
        local flags = SMODS.trigger_effects(effects, card)
        if flags.add_to_hand then splashed = true end
        if flags.remove_from_hand then unsplashed = true end
        if splashed and not unsplashed then table.insert(final_scoring_hand, card) end
    end
        
    scoring_hand = final_scoring_hand
    
    if #scoring_hand <= 4 then
        self.triggered = true
        return true
    end
end
'''
match_indent = true

# Disable drawing cards
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "if G.GAME.blind.name == 'The Serpent' and"
position = 'before'
payload = '''
if G.GAME.modifiers.inflated and not (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) and (G.GAME.current_round.hands_played > 0 or G.GAME.current_round.discards_used > 0) then
    hand_space = 0
end
'''
match_indent = true

# Survivor reroll disable
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if ((G.GAME.dollars-G.GAME.bankrupt_at) - G.GAME.current_round.reroll_cost < 0) and G.GAME.current_round.reroll_cost ~= 0 then"
position = 'at'
payload = "if ((G.GAME.dollars-G.GAME.bankrupt_at) - G.GAME.current_round.reroll_cost < 0) and G.GAME.current_round.reroll_cost ~= 0 or G.GAME.modifiers.no_shop_rerolls then"
match_indent = true

# 2mp score requirement scaling
[[patches]]
[patches.pattern]
target = "functions/misc_functions.lua"
pattern = '''
local amounts = {
    300,  1000, 3200,  9000,  25000,  60000,  110000,  200000
    --300,  1000, 3000,  8000,  22000,  50000,  90000,  180000
}
'''
position = 'after'
payload = '''
if G.GAME.modifiers._2mp or G.GAME.modifiers._2mp_expert then
    amounts = {
        300,  1200,  5000,  18000,  60000,  180000,  450000,  1000000
    }
end
'''
match_indent = true
