[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Disable gold cards
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "local h_dollars = self:get_h_dollars()"
position = "at"
payload = '''
local h_dollars = (G.GAME.modifiers.disable_gold_card_money and self.ability.name == 'Gold Card') and 0 or self:get_h_dollars()
'''
match_indent = true