[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.play and G.play.cards[1] then return end"
position = "after"
payload = '''
if G.GAME.modifiers.gorgon_storm then
    local value_counts = {}
    local duplicate_found = false
    for _, card in ipairs(G.hand.highlighted) do
        local v = card.base.value
        value_counts[v] = (value_counts[v] or 0) + 1
    end
    for value, count in pairs(value_counts) do
        if count > 1 then
            duplicate_found = true
        end
    end

    if not duplicate_found then
        G.E_MANAGER:add_event(Event({
            trigger = 'after',
            delay = 1,
            func = function()
                G.STATE = G.STATES.GAME_OVER
                G.STATE_COMPLETE = false
                return true
            end
        }))
    end
end
'''
match_indent = true