[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Heart of Thunder Double Tag
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = 'add_tag(_tag.config.ref_table)'
position = 'before'
payload = '''
local thunders = find_joker('Heart of Thunder')
for k, v in pairs(thunders) do
    if SMODS.pseudorandom_probability(card, 'thunder', G.P_CENTERS.j_bloons_thunder.config.extra.num, G.P_CENTERS.j_bloons_thunder.config.extra.denom, 'thunder') then
        add_tag(Tag('tag_double'))
    end
end
'''
match_indent = true