[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Disable drawing cards
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = "if G.GAME.blind.name == 'The Serpent' and"
position = 'before'
payload = '''
if G.GAME.modifiers.inflated and not (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) and (G.GAME.current_round.hands_played > 0 or G.GAME.current_round.discards_used > 0) then
    hand_space = 0
end
'''
match_indent = true