[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
        G.VIBRATION = G.VIBRATION + 1
        return true
end)}))
'''
position = 'after'
payload = '''

Bloonlatro.main_menu()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = "if e and e.config.id == 'restart_button' then G.GAME.viewed_back = nil end"
position = 'after'
payload = "Bloonlatro.restart_boss_challenge = Bloonlatro.boss_challenge"
match_indent = true