[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = 'game.lua'
pattern = '''
        G.VIBRATION = G.VIBRATION + 1
        return true
end)}))
'''
position = 'after'
payload = '''

Bloonlatro.main_menu()
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
G.STAGE == G.STAGES.MAIN_MENU and {
  label = localize('b_challenges'),
	tab_definition_function = G.UIDEF.challenges,
  tab_definition_function_args = from_game_over,
  chosen = _challenge_chosen
} or nil,
'''
position = 'at'
payload = '''
G.STAGE == G.STAGES.MAIN_MENU and {
  label = localize('b_challenges'),
	tab_definition_function = G.UIDEF.challenges,
  tab_definition_function_args = from_game_over,
  chosen = _challenge_chosen
} or 
{
	label = "Bosses",
	tab_definition_function = G.FUNCS.create_bloonlatro_boss_ui,
	tab_definition_function_args = "run_tab", from_game_over,
},
'''
match_indent = true