[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Ring of Fire meteor card
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''if (v.type == 'Base' or v.type == 'Enhanced') and G.GAME.used_vouchers["v_illusion"] and pseudorandom(pseudoseed('illusion')) > 0.8 then'''
position = 'before'
payload = '''
local rof_amount = #find_joker('Ring of Fire')
if (v.type == 'Base' or v.type == 'Enhanced') and (rof_amount > 0) then
    local meteor_rate = G.P_CENTERS.j_bloons_ring_of_fire.config.extra.rate * rof_amount
    if SMODS.pseudorandom_probability(card, 'meteor_rate', meteor_rate, G.GAME.playing_card_rate, 'meteor_rate', true) then
        card:set_ability('m_bloons_meteor')
    end
end
'''
match_indent = true

# Magic Trick adding to card rate instead of setting it
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'G.GAME.playing_card_rate = center_table.extra'
position = 'before'
payload = 'G.GAME.playing_card_rate = G.GAME.playing_card_rate + center_table.extra'
match_indent = true