[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Ninja full slots select
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
G.FUNCS.can_select_card = function(e)
  local card = e.config.ref_table
'''
position = 'after'
payload = '''
  if card.ability.set == 'Joker' and card.ability.tower_info and card.ability.tower_info.base == 'Ninja Monkey' and card:is_rarity('Common') then
    e.config.colour = G.C.GREEN
    e.config.button = 'use_card'
    return
  end
'''
match_indent = true

# Ninja full slots buy
[[patches]]
[patches.pattern]
target = 'functions/button_callbacks.lua'
pattern = '''
G.FUNCS.check_for_buy_space = function(card)
'''
position = 'after'
payload = '''
  if card.ability.set == 'Joker' and card.ability.tower_info and card.ability.tower_info.base == 'Ninja Monkey' and card:is_rarity('Common') then
    return true
  end
'''
match_indent = true