[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Shinobi Tactics reappear
[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "elseif not (G.GAME.used_jokers[v.key] and not pool_opts.allow_duplicates and not SMODS.showman(v.key)) and"
position = 'at'
payload = "elseif (not G.GAME.used_jokers[v.key] or (v.config.base == 'ninja' and #find_joker('Shinobi Tactics') > 0) or pool_opts.allow_duplicates or SMODS.showman(v.key)) and"
match_indent = true
