[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''
function create_UIBox_blind_tag(blind_choice, run_info)
'''
position = "after"
match_indent = true
payload = '''
  local center = G.GAME.selected_back and G.GAME.selected_back.effect and G.GAME.selected_back.effect.center
  local boss = center and center.get_boss_blind and center:get_boss_blind()

  local disable_skip =
    G.GAME.modifiers.no_skipping_blinds or 
    (boss and boss.key == 'bl_bloons_diamondback_head' and G.GAME.round_resets.ante % G.GAME.win_ante == 0 and G.GAME.round_resets.ante >= 2)

  if disable_skip then
    return
  end
'''