[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''
if _tag and _tag_container then 
  _tag_container.children[2].config.draw_after = false
  _tag_container.children[2].config.colour = G.C.BLACK
  _tag.children[2].config.button = 'skip_blind'
  _tag.config.outline_colour = adjust_alpha(G.C.BLUE, 0.5)
  _tag.children[2].config.hover = true
  _tag.children[2].config.colour = G.C.RED
  _tag.children[2].children[1].config.colour = G.C.UI.TEXT_LIGHT
  local _sprite = _tag.config.ref_table
  _sprite.config.force_focus = nil
end
'''
position = "at"
payload = '''
if _tag and _tag_container then 
  _tag_container.children[2].config.draw_after = false
  _tag_container.children[2].config.colour = G.C.BLACK
  
  if G.GAME.modifiers.no_skipping_blinds then
    _tag.children[2].config.button = nil
    _tag.children[2].config.colour = G.C.UI.BACKGROUND_INACTIVE
    _tag.children[2].children[1].config.colour = G.C.UI.TEXT_INACTIVE
  else
    _tag.children[2].config.button = 'skip_blind'
    _tag.config.outline_colour = adjust_alpha(G.C.BLUE, 0.5)
    _tag.children[2].config.colour = G.C.RED
    _tag.children[2].children[1].config.colour = G.C.UI.TEXT_LIGHT
  end
  
  _tag.children[2].config.hover = true
  local _sprite = _tag.config.ref_table
  _sprite.config.force_focus = nil
end
'''
match_indent = true