[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Sun Avatar Planet Xmult
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = "function Card:calculate_joker(context)"
position = 'after'
payload = '''
if self.ability.set == "Planet" and not self.debuff then
    if context.other_joker and context.other_joker.ability.name == 'Sun Avatar' and not context.other_joker.debuff then
        local triggers = 1 + context.other_joker.ability.extra.blueprint_amount
        
        local sav_mult = (self.ability.consumeable.hand_type == context.scoring_name) and 
                         G.P_CENTERS.j_bloons_sav.config.extra.Xmult_match or 
                         G.P_CENTERS.j_bloons_sav.config.extra.Xmult

        for i = 1, triggers do
            mult = mult * sav_mult
            update_hand_text({sound = 'multhit2', pitch = 0.9, volume = 0.6, delay = 0.3}, {handname=handname, chips = hand_chips, mult = mult, level = level})
            G.E_MANAGER:add_event(Event({
                func = function()
                    context.other_joker:juice_up(0.5, 0.5)
                    return true
                end
            }))
            card_eval_status_text(self, 'extra', nil, nil, nil, {
                message = localize{type = 'variable', key = 'a_xmult', vars = {sav_mult}},
                colour = G.C.RED
            })
        end
    end
end
'''
match_indent = true