[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = '''
self.chips = get_blind_amount(G.GAME.round_resets.ante)*self.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if G.GAME.used_vouchers.v_bloons_big_bloon_blueprints and self.boss then
    percent = G.P_CENTERS['v_bloons_big_bloon_blueprints'].config.extra.percent
    self.chips = self.chips - self.chips * percent / 100.0
elseif G.GAME.used_vouchers.v_bloons_big_bloon_sabotage then
    percent = G.P_CENTERS['v_bloons_big_bloon_sabotage'].config.extra.percent
    self.chips = self.chips - self.chips * percent / 100.0
end
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
local blind_amt = get_blind_amount(G.GAME.round_resets.blind_ante)*blind_choice.config.mult*G.GAME.starting_params.ante_scaling
'''
position = "after"
payload = '''
if G.GAME.used_vouchers.v_bloons_big_bloon_blueprints and type == 'Boss' then
    percent = G.P_CENTERS['v_bloons_big_bloon_blueprints'].config.extra.percent
    blind_amt = blind_amt - blind_amt * percent / 100.0
elseif G.GAME.used_vouchers.v_bloons_big_bloon_sabotage then
    percent = G.P_CENTERS['v_bloons_big_bloon_sabotage'].config.extra.percent
    blind_amt = blind_amt - blind_amt * percent / 100.0
end
'''
match_indent = true
times = 1
